name: Release 

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t vodenizeko/action-app
    - run: echo '${{secrets.DOCKER_PASSWORD}}' | docker login -u ${{secrets.USERNAME}} --pasword stdin
    - run: docker push vodenizeko/action-app